import { createTests } from '../vitest-extended/createTests';
import { describe } from 'vitest';
import { name } from './constants';
import { exclude } from './vitest';

type Fn = (...args: any) => any;

describe('vitest - exclude', () => {
  const environment = 'node';
  const enabled = true;
  const enforce = 'pre';

  const fn = async (...args: Parameters<typeof exclude>) => {
    const { name, enforce, config: c } = exclude(...args);
    const fn = c as Fn;
    const config = await fn({
      test: { environment, coverage: { enabled } },
    });
    return { config, name, enforce };
  };

  const { acceptation, success } = createTests(fn);

  describe('#00 => Acceptation', acceptation);

  describe(
    '#01 => Success',
    success(
      {
        invite: 'No ignore',
        parameters: [],
        expected: {
          name,
          enforce,
          config: {
            test: {
              include: [
                'src/build-tests/getTypescriptOutdir.test.ts',
                'src/index.test.ts',
                'src/rolldown-config/__tests__/bemedev/declarationMap.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/declarationMap.test.ts',
                'src/rolldown-config/__tests__/bemedev/default.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/default.test.ts',
                'src/rolldown-config/__tests__/bemedev/notOmitAFile.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/notOmitAFile.test.ts',
                'src/rolldown-config/__tests__/bemedev/omitAFile.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/omitAFile.test.ts',
                'src/rolldown-config/__tests__/withoutOptions.test.ts',
                'src/vitest-exclude/Counter.test.tsx',
                'src/vitest-exclude/vitest.test.ts',
                'src/vitest-extended/createTests.cov.test.ts',
                'src/vitest-extended/done.test.ts',
                'src/vitest-extended/each/pass.cov.test.ts',
                'src/vitest-extended/fakeWaiter.test.ts',
                'src/vitest-extended/fixtures/coverage.test.ts',
                'src/vitest-extended/fixtures/partialCall.test.ts',
                'src/vitest-extended/fixtures/toUpper.test.ts',
                'src/vitest-extended/fixtures/zod.test.ts',
                'src/vitest-extended/isFunction.test.ts',
              ],
              environment,
              coverage: {
                enabled,
                include: [
                  'src/build-tests/addTarball.ts',
                  'src/build-tests/buildPackageJson.ts',
                  'src/build-tests/cleanup.ts',
                  'src/build-tests/cli/cli.ts',
                  'src/build-tests/cli/index.ts',
                  'src/build-tests/cli/post.ts',
                  'src/build-tests/cli/pre.ts',
                  'src/build-tests/cli/test.ts',
                  'src/build-tests/constants.ts',
                  'src/build-tests/getRelativePath.ts',
                  'src/build-tests/getTypescriptOutdir.test.ts',
                  'src/build-tests/getTypescriptOutdir.ts',
                  'src/build-tests/index.ts',
                  'src/build-tests/pack.ts',
                  'src/index.test.ts',
                  'src/index.ts',
                  'src/rolldown-config/__tests__/bemedev/declarationMap.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/declarationMap.test.ts',
                  'src/rolldown-config/__tests__/bemedev/default.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/default.test.ts',
                  'src/rolldown-config/__tests__/bemedev/notOmitAFile.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/notOmitAFile.test.ts',
                  'src/rolldown-config/__tests__/bemedev/omitAFile.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/omitAFile.test.ts',
                  'src/rolldown-config/__tests__/constants.ts',
                  'src/rolldown-config/__tests__/fixtures.ts',
                  'src/rolldown-config/__tests__/withoutOptions.test.ts',
                  'src/rolldown-config/config.ts',
                  'src/rolldown-config/constants.ts',
                  'src/rolldown-config/helpers.ts',
                  'src/rolldown-config/index.ts',
                  'src/rolldown-config/input.ts',
                  'src/rolldown-config/output.ts',
                  'src/rolldown-config/plugins/alias.ts',
                  'src/rolldown-config/plugins/circulars.ts',
                  'src/rolldown-config/plugins/clean.ts',
                  'src/rolldown-config/plugins/externals.ts',
                  'src/rolldown-config/plugins/index.ts',
                  'src/rolldown-config/plugins/tsPaths.ts',
                  'src/rolldown-config/plugins/typescript.config.ts',
                  'src/rolldown-config/plugins/typescript.ts',
                  'src/rolldown-config/types.ts',
                  'src/rolldown-config/utils.ts',
                  'src/utils/index.ts',
                  'src/utils/sleep.ts',
                  'src/utils/types.ts',
                  'src/vitest-alias/index.ts',
                  'src/vitest-alias/vitest.ts',
                  'src/vitest-exclude/Counter.test.tsx',
                  'src/vitest-exclude/Counter.tsx',
                  'src/vitest-exclude/constants.ts',
                  'src/vitest-exclude/index.ts',
                  'src/vitest-exclude/types.ts',
                  'src/vitest-exclude/vitest.test.ts',
                  'src/vitest-exclude/vitest.ts',
                  'src/vitest-exclude/vitest.utils.ts',
                  'src/vitest-extended/acceptation.ts',
                  'src/vitest-extended/bemedev/globals/types.ts',
                  'src/vitest-extended/bemedev/globals/utils/_unknown.ts',
                  'src/vitest-extended/createTests.cov.test.ts',
                  'src/vitest-extended/createTests.ts',
                  'src/vitest-extended/createTests.types.ts',
                  'src/vitest-extended/done.test.ts',
                  'src/vitest-extended/done.ts',
                  'src/vitest-extended/each/error.ts',
                  'src/vitest-extended/each/error.types.ts',
                  'src/vitest-extended/each/index.ts',
                  'src/vitest-extended/each/pass.cov.test.ts',
                  'src/vitest-extended/each/pass.ts',
                  'src/vitest-extended/each/pass.types.ts',
                  'src/vitest-extended/fakeWaiter.test.ts',
                  'src/vitest-extended/fakeWaiter.ts',
                  'src/vitest-extended/fixtures/coverage.test.ts',
                  'src/vitest-extended/fixtures/coverage.ts',
                  'src/vitest-extended/fixtures/partialCall.test.ts',
                  'src/vitest-extended/fixtures/partialCall.ts',
                  'src/vitest-extended/fixtures/toUpper.test.ts',
                  'src/vitest-extended/fixtures/toUpper.ts',
                  'src/vitest-extended/fixtures/vitest.ts',
                  'src/vitest-extended/fixtures/zod.fixtures.ts',
                  'src/vitest-extended/fixtures/zod.test.ts',
                  'src/vitest-extended/fixtures/zod.ts',
                  'src/vitest-extended/identity.ts',
                  'src/vitest-extended/index.ts',
                  'src/vitest-extended/isDefined.ts',
                  'src/vitest-extended/isFunction.test.ts',
                  'src/vitest-extended/isFunction.ts',
                  'src/vitest-extended/toArray.ts',
                  'src/vitest-extended/toStringFlat.ts',
                  'src/vitest-extended/types.test-d.ts',
                  'src/vitest-extended/types.ts',
                ],
              },
            },
          },
        },
      },

      {
        invite: 'Ignore all test files in coverage',
        parameters: [{ ignoreCoverageFiles: ['**/*.test.t{s,sx}'] }],
        expected: {
          name,
          enforce,
          config: {
            test: {
              environment,
              include: [
                'src/build-tests/getTypescriptOutdir.test.ts',
                'src/index.test.ts',
                'src/rolldown-config/__tests__/bemedev/declarationMap.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/declarationMap.test.ts',
                'src/rolldown-config/__tests__/bemedev/default.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/default.test.ts',
                'src/rolldown-config/__tests__/bemedev/notOmitAFile.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/notOmitAFile.test.ts',
                'src/rolldown-config/__tests__/bemedev/omitAFile.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/omitAFile.test.ts',
                'src/rolldown-config/__tests__/withoutOptions.test.ts',
                'src/vitest-exclude/Counter.test.tsx',
                'src/vitest-exclude/vitest.test.ts',
                'src/vitest-extended/createTests.cov.test.ts',
                'src/vitest-extended/done.test.ts',
                'src/vitest-extended/each/pass.cov.test.ts',
                'src/vitest-extended/fakeWaiter.test.ts',
                'src/vitest-extended/fixtures/coverage.test.ts',
                'src/vitest-extended/fixtures/partialCall.test.ts',
                'src/vitest-extended/fixtures/toUpper.test.ts',
                'src/vitest-extended/fixtures/zod.test.ts',
                'src/vitest-extended/isFunction.test.ts',
              ],

              coverage: {
                enabled,
                include: [
                  'src/build-tests/addTarball.ts',
                  'src/build-tests/buildPackageJson.ts',
                  'src/build-tests/cleanup.ts',
                  'src/build-tests/cli/cli.ts',
                  'src/build-tests/cli/index.ts',
                  'src/build-tests/cli/post.ts',
                  'src/build-tests/cli/pre.ts',
                  'src/build-tests/cli/test.ts',
                  'src/build-tests/constants.ts',
                  'src/build-tests/getRelativePath.ts',
                  'src/build-tests/getTypescriptOutdir.ts',
                  'src/build-tests/index.ts',
                  'src/build-tests/pack.ts',
                  'src/index.ts',
                  'src/rolldown-config/__tests__/constants.ts',
                  'src/rolldown-config/__tests__/fixtures.ts',
                  'src/rolldown-config/config.ts',
                  'src/rolldown-config/constants.ts',
                  'src/rolldown-config/helpers.ts',
                  'src/rolldown-config/index.ts',
                  'src/rolldown-config/input.ts',
                  'src/rolldown-config/output.ts',
                  'src/rolldown-config/plugins/alias.ts',
                  'src/rolldown-config/plugins/circulars.ts',
                  'src/rolldown-config/plugins/clean.ts',
                  'src/rolldown-config/plugins/externals.ts',
                  'src/rolldown-config/plugins/index.ts',
                  'src/rolldown-config/plugins/tsPaths.ts',
                  'src/rolldown-config/plugins/typescript.config.ts',
                  'src/rolldown-config/plugins/typescript.ts',
                  'src/rolldown-config/types.ts',
                  'src/rolldown-config/utils.ts',
                  'src/utils/index.ts',
                  'src/utils/sleep.ts',
                  'src/utils/types.ts',
                  'src/vitest-alias/index.ts',
                  'src/vitest-alias/vitest.ts',
                  'src/vitest-exclude/Counter.tsx',
                  'src/vitest-exclude/constants.ts',
                  'src/vitest-exclude/index.ts',
                  'src/vitest-exclude/types.ts',
                  'src/vitest-exclude/vitest.ts',
                  'src/vitest-exclude/vitest.utils.ts',
                  'src/vitest-extended/acceptation.ts',
                  'src/vitest-extended/bemedev/globals/types.ts',
                  'src/vitest-extended/bemedev/globals/utils/_unknown.ts',
                  'src/vitest-extended/createTests.ts',
                  'src/vitest-extended/createTests.types.ts',
                  'src/vitest-extended/done.ts',
                  'src/vitest-extended/each/error.ts',
                  'src/vitest-extended/each/error.types.ts',
                  'src/vitest-extended/each/index.ts',
                  'src/vitest-extended/each/pass.ts',
                  'src/vitest-extended/each/pass.types.ts',
                  'src/vitest-extended/fakeWaiter.ts',
                  'src/vitest-extended/fixtures/coverage.ts',
                  'src/vitest-extended/fixtures/partialCall.ts',
                  'src/vitest-extended/fixtures/toUpper.ts',
                  'src/vitest-extended/fixtures/vitest.ts',
                  'src/vitest-extended/fixtures/zod.fixtures.ts',
                  'src/vitest-extended/fixtures/zod.ts',
                  'src/vitest-extended/identity.ts',
                  'src/vitest-extended/index.ts',
                  'src/vitest-extended/isDefined.ts',
                  'src/vitest-extended/isFunction.ts',
                  'src/vitest-extended/toArray.ts',
                  'src/vitest-extended/toStringFlat.ts',
                  'src/vitest-extended/types.test-d.ts',
                  'src/vitest-extended/types.ts',
                ],
              },
            },
          },
        },
      },

      {
        invite: 'Ignore all index files',
        parameters: [{ ignoreCoverageFiles: ['**/index.ts'] }],
        expected: {
          name,
          enforce,
          config: {
            test: {
              environment,
              include: [
                'src/build-tests/getTypescriptOutdir.test.ts',
                'src/index.test.ts',
                'src/rolldown-config/__tests__/bemedev/declarationMap.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/declarationMap.test.ts',
                'src/rolldown-config/__tests__/bemedev/default.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/default.test.ts',
                'src/rolldown-config/__tests__/bemedev/notOmitAFile.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/notOmitAFile.test.ts',
                'src/rolldown-config/__tests__/bemedev/omitAFile.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/omitAFile.test.ts',
                'src/rolldown-config/__tests__/withoutOptions.test.ts',
                'src/vitest-exclude/Counter.test.tsx',
                'src/vitest-exclude/vitest.test.ts',
                'src/vitest-extended/createTests.cov.test.ts',
                'src/vitest-extended/done.test.ts',
                'src/vitest-extended/each/pass.cov.test.ts',
                'src/vitest-extended/fakeWaiter.test.ts',
                'src/vitest-extended/fixtures/coverage.test.ts',
                'src/vitest-extended/fixtures/partialCall.test.ts',
                'src/vitest-extended/fixtures/toUpper.test.ts',
                'src/vitest-extended/fixtures/zod.test.ts',
                'src/vitest-extended/isFunction.test.ts',
              ],

              coverage: {
                enabled,
                include: [
                  'src/build-tests/addTarball.ts',
                  'src/build-tests/buildPackageJson.ts',
                  'src/build-tests/cleanup.ts',
                  'src/build-tests/cli/cli.ts',
                  'src/build-tests/cli/post.ts',
                  'src/build-tests/cli/pre.ts',
                  'src/build-tests/cli/test.ts',
                  'src/build-tests/constants.ts',
                  'src/build-tests/getRelativePath.ts',
                  'src/build-tests/getTypescriptOutdir.test.ts',
                  'src/build-tests/getTypescriptOutdir.ts',
                  'src/build-tests/pack.ts',
                  'src/index.test.ts',
                  'src/rolldown-config/__tests__/bemedev/declarationMap.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/declarationMap.test.ts',
                  'src/rolldown-config/__tests__/bemedev/default.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/default.test.ts',
                  'src/rolldown-config/__tests__/bemedev/notOmitAFile.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/notOmitAFile.test.ts',
                  'src/rolldown-config/__tests__/bemedev/omitAFile.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/omitAFile.test.ts',
                  'src/rolldown-config/__tests__/constants.ts',
                  'src/rolldown-config/__tests__/fixtures.ts',
                  'src/rolldown-config/__tests__/withoutOptions.test.ts',
                  'src/rolldown-config/config.ts',
                  'src/rolldown-config/constants.ts',
                  'src/rolldown-config/helpers.ts',
                  'src/rolldown-config/input.ts',
                  'src/rolldown-config/output.ts',
                  'src/rolldown-config/plugins/alias.ts',
                  'src/rolldown-config/plugins/circulars.ts',
                  'src/rolldown-config/plugins/clean.ts',
                  'src/rolldown-config/plugins/externals.ts',
                  'src/rolldown-config/plugins/tsPaths.ts',
                  'src/rolldown-config/plugins/typescript.config.ts',
                  'src/rolldown-config/plugins/typescript.ts',
                  'src/rolldown-config/types.ts',
                  'src/rolldown-config/utils.ts',
                  'src/utils/sleep.ts',
                  'src/utils/types.ts',
                  'src/vitest-alias/vitest.ts',
                  'src/vitest-exclude/Counter.test.tsx',
                  'src/vitest-exclude/Counter.tsx',
                  'src/vitest-exclude/constants.ts',
                  'src/vitest-exclude/types.ts',
                  'src/vitest-exclude/vitest.test.ts',
                  'src/vitest-exclude/vitest.ts',
                  'src/vitest-exclude/vitest.utils.ts',
                  'src/vitest-extended/acceptation.ts',
                  'src/vitest-extended/bemedev/globals/types.ts',
                  'src/vitest-extended/bemedev/globals/utils/_unknown.ts',
                  'src/vitest-extended/createTests.cov.test.ts',
                  'src/vitest-extended/createTests.ts',
                  'src/vitest-extended/createTests.types.ts',
                  'src/vitest-extended/done.test.ts',
                  'src/vitest-extended/done.ts',
                  'src/vitest-extended/each/error.ts',
                  'src/vitest-extended/each/error.types.ts',
                  'src/vitest-extended/each/pass.cov.test.ts',
                  'src/vitest-extended/each/pass.ts',
                  'src/vitest-extended/each/pass.types.ts',
                  'src/vitest-extended/fakeWaiter.test.ts',
                  'src/vitest-extended/fakeWaiter.ts',
                  'src/vitest-extended/fixtures/coverage.test.ts',
                  'src/vitest-extended/fixtures/coverage.ts',
                  'src/vitest-extended/fixtures/partialCall.test.ts',
                  'src/vitest-extended/fixtures/partialCall.ts',
                  'src/vitest-extended/fixtures/toUpper.test.ts',
                  'src/vitest-extended/fixtures/toUpper.ts',
                  'src/vitest-extended/fixtures/vitest.ts',
                  'src/vitest-extended/fixtures/zod.fixtures.ts',
                  'src/vitest-extended/fixtures/zod.test.ts',
                  'src/vitest-extended/fixtures/zod.ts',
                  'src/vitest-extended/identity.ts',
                  'src/vitest-extended/isDefined.ts',
                  'src/vitest-extended/isFunction.test.ts',
                  'src/vitest-extended/isFunction.ts',
                  'src/vitest-extended/toArray.ts',
                  'src/vitest-extended/toStringFlat.ts',
                  'src/vitest-extended/types.test-d.ts',
                  'src/vitest-extended/types.ts',
                ],
              },
            },
          },
        },
      },

      {
        invite: 'Ignore all index files and tsx files',
        parameters: [
          {
            ignoreCoverageFiles: ['**/index.ts', '**/*.tsx'],
            ignoreTestFiles: ['**/*.tsx'],
          },
        ],
        expected: {
          name,
          enforce,
          config: {
            test: {
              environment,
              include: [
                'src/build-tests/getTypescriptOutdir.test.ts',
                'src/index.test.ts',
                'src/rolldown-config/__tests__/bemedev/declarationMap.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/declarationMap.test.ts',
                'src/rolldown-config/__tests__/bemedev/default.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/default.test.ts',
                'src/rolldown-config/__tests__/bemedev/notOmitAFile.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/notOmitAFile.test.ts',
                'src/rolldown-config/__tests__/bemedev/omitAFile.built.test.ts',
                'src/rolldown-config/__tests__/bemedev/omitAFile.test.ts',
                'src/rolldown-config/__tests__/withoutOptions.test.ts',
                'src/vitest-exclude/vitest.test.ts',
                'src/vitest-extended/createTests.cov.test.ts',
                'src/vitest-extended/done.test.ts',
                'src/vitest-extended/each/pass.cov.test.ts',
                'src/vitest-extended/fakeWaiter.test.ts',
                'src/vitest-extended/fixtures/coverage.test.ts',
                'src/vitest-extended/fixtures/partialCall.test.ts',
                'src/vitest-extended/fixtures/toUpper.test.ts',
                'src/vitest-extended/fixtures/zod.test.ts',
                'src/vitest-extended/isFunction.test.ts',
              ],

              coverage: {
                enabled,
                include: [
                  'src/build-tests/addTarball.ts',
                  'src/build-tests/buildPackageJson.ts',
                  'src/build-tests/cleanup.ts',
                  'src/build-tests/cli/cli.ts',
                  'src/build-tests/cli/post.ts',
                  'src/build-tests/cli/pre.ts',
                  'src/build-tests/cli/test.ts',
                  'src/build-tests/constants.ts',
                  'src/build-tests/getRelativePath.ts',
                  'src/build-tests/getTypescriptOutdir.test.ts',
                  'src/build-tests/getTypescriptOutdir.ts',
                  'src/build-tests/pack.ts',
                  'src/index.test.ts',
                  'src/rolldown-config/__tests__/bemedev/declarationMap.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/declarationMap.test.ts',
                  'src/rolldown-config/__tests__/bemedev/default.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/default.test.ts',
                  'src/rolldown-config/__tests__/bemedev/notOmitAFile.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/notOmitAFile.test.ts',
                  'src/rolldown-config/__tests__/bemedev/omitAFile.built.test.ts',
                  'src/rolldown-config/__tests__/bemedev/omitAFile.test.ts',
                  'src/rolldown-config/__tests__/constants.ts',
                  'src/rolldown-config/__tests__/fixtures.ts',
                  'src/rolldown-config/__tests__/withoutOptions.test.ts',
                  'src/rolldown-config/config.ts',
                  'src/rolldown-config/constants.ts',
                  'src/rolldown-config/helpers.ts',
                  'src/rolldown-config/input.ts',
                  'src/rolldown-config/output.ts',
                  'src/rolldown-config/plugins/alias.ts',
                  'src/rolldown-config/plugins/circulars.ts',
                  'src/rolldown-config/plugins/clean.ts',
                  'src/rolldown-config/plugins/externals.ts',
                  'src/rolldown-config/plugins/tsPaths.ts',
                  'src/rolldown-config/plugins/typescript.config.ts',
                  'src/rolldown-config/plugins/typescript.ts',
                  'src/rolldown-config/types.ts',
                  'src/rolldown-config/utils.ts',
                  'src/utils/sleep.ts',
                  'src/utils/types.ts',
                  'src/vitest-alias/vitest.ts',
                  'src/vitest-exclude/constants.ts',
                  'src/vitest-exclude/types.ts',
                  'src/vitest-exclude/vitest.test.ts',
                  'src/vitest-exclude/vitest.ts',
                  'src/vitest-exclude/vitest.utils.ts',
                  'src/vitest-extended/acceptation.ts',
                  'src/vitest-extended/bemedev/globals/types.ts',
                  'src/vitest-extended/bemedev/globals/utils/_unknown.ts',
                  'src/vitest-extended/createTests.cov.test.ts',
                  'src/vitest-extended/createTests.ts',
                  'src/vitest-extended/createTests.types.ts',
                  'src/vitest-extended/done.test.ts',
                  'src/vitest-extended/done.ts',
                  'src/vitest-extended/each/error.ts',
                  'src/vitest-extended/each/error.types.ts',
                  'src/vitest-extended/each/pass.cov.test.ts',
                  'src/vitest-extended/each/pass.ts',
                  'src/vitest-extended/each/pass.types.ts',
                  'src/vitest-extended/fakeWaiter.test.ts',
                  'src/vitest-extended/fakeWaiter.ts',
                  'src/vitest-extended/fixtures/coverage.test.ts',
                  'src/vitest-extended/fixtures/coverage.ts',
                  'src/vitest-extended/fixtures/partialCall.test.ts',
                  'src/vitest-extended/fixtures/partialCall.ts',
                  'src/vitest-extended/fixtures/toUpper.test.ts',
                  'src/vitest-extended/fixtures/toUpper.ts',
                  'src/vitest-extended/fixtures/vitest.ts',
                  'src/vitest-extended/fixtures/zod.fixtures.ts',
                  'src/vitest-extended/fixtures/zod.test.ts',
                  'src/vitest-extended/fixtures/zod.ts',
                  'src/vitest-extended/identity.ts',
                  'src/vitest-extended/isDefined.ts',
                  'src/vitest-extended/isFunction.test.ts',
                  'src/vitest-extended/isFunction.ts',
                  'src/vitest-extended/toArray.ts',
                  'src/vitest-extended/toStringFlat.ts',
                  'src/vitest-extended/types.test-d.ts',
                  'src/vitest-extended/types.ts',
                ],
              },
            },
          },
        },
      },
    ),
  );
});
